filebeat.inputs:
  - type: filestream
    id: filestream-logs
    enabled: true
    paths:
      - /usr/share/filebeat/logs/*.log
    parsers:
      - multiline:
          type: pattern
          pattern: '^{'
          negate: true
          match: after

output.logstash:
  hosts: ["logstash:5044"]
