name: stocks
networks:
  dev:


services:
  # region --------------- APPS -------------


  user.api.stocks:
     container_name: user.api.stocks
     build:
       context: ./src/apps
       dockerfile: Dockerfile
     depends_on:
       - postgres.db.stocks
     restart: unless-stopped
     networks:
       - dev
  # end --------------------------------------

  # end --------------------------------------

  # region --------------- DB ----------------

  postgres.db.stocks:
    image: postgres:17.2-alpine
    container_name: postgres.db.stocks
    restart: unless-stopped
    networks:
      - dev
# end ---------------------------------------