services:

  es01:
    container_name: es01
    image: elasticsearch:8.11.4
    environment:
      - "ES_JAVA_OPTS=-Xmx1g -Xms1g"
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
      nproc:
        soft: 4096
        hard: 4096
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
      - ./elasticsearch/config.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
    networks:
      - elk

  kibana:
    container_name: kibana
    image: kibana:8.11.4
    depends_on:
      - es01
    healthcheck:
      test: ["CMD-SHELL", "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'"]
      interval: 10s
      timeout: 10s
      retries: 120
    ports:
      - "5601:5601"
    volumes:
      - kibana_data:/usr/share/kibana/data
      - ./kibana/config.yml:/usr/share/kibana/config/kibana.yml:ro
    networks:
      - elk

  logstash:
    container_name: logstash
    image: logstash:8.11.4
    depends_on:
      - es01
    ports:
      - "5044:5044"
    volumes:
      - ./logstash/config.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./logstash/pipelines/:/usr/share/logstash/pipeline:ro
      - logstash_data:/usr/share/logstash/data
    networks:
      - elk

  beats:
    container_name: beats
    image: elastic/filebeat:8.11.4
    command: filebeat -e -strict.perms=false
    depends_on:
      - logstash
    volumes:
      - ./filebeat/config.yml:/usr/share/filebeat/filebeat.yml:ro
      - filebeat_data:/usr/share/filebeat/data
      - online_logs:/usr/share/filebeat/logs:ro
    networks:
      - elk

volumes:
  elastic_data:
  kibana_data:
  logstash_data:
  filebeat_data:
  online_logs:
    external: true

networks:
  elk: